### ISSUE TITLE
Failed to extract some commands.

### ISSUE THREAD

**Issue by chebee7i** [ttsiodras/utils#4]
Here's an example that doesn't quite work.
```console
$ sleep 300 &
[1] 103453

$ ls -l /proc/103453/exe
lrwxrwxrwx 1 username groupname 0 Aug  6 14:34 /proc/103453/exe -> /usr/bin/sleep

$ showBashCmdline.sh 103453
This is not a bash PID
```

**Comment by ttsiodras** [comment]
...which is exactly what you'd expect to see, since the process ID in question (`103453`) is not a *bash* process ID - it's the process ID of your `/usr/bin/sleep`.  The script shows the command line running inside a *bash* process.

**Comment by chebee7i** [comment]
🤷 ok.

I was coming from the perspective that one wanted to capture the command line for whatever one happened to launch from a bash terminal. Certainly that was the original spirit of https://unix.stackexchange.com/questions/159010/how-can-i-see-the-exact-command-line-being-executed-inside-some-bash-instance/159012#159012.
